
suppressMessages(library(tidyverse))
list.files("Data")

# Official Data: (https://www.kaggle.com/c/march-machine-learning-mania-2017/data)
Teams <- read.csv("Data/Teams.csv")
Seasons <- read.csv("Data/Seasons.csv")
RegularSeasonCompactResults <- read.csv("Data/RegularSeasonCompactResults.csv")
  # RegularSeasonCompactResults_2017 <- read.csv("Data/CompactResults_PrelimThru2017Day87.csv")
  # RegularSeasonCompactResults_2017 <- read.csv("Data/2017_PrelimThruDay124_CompactResults.csv")
  RegularSeasonCompactResults_2017 <- read.csv("Data/2017_Final_CompactResults.csv")
RegularSeasonDetailedResults <- read.csv("Data/RegularSeasonDetailedResults.csv")
  # RegularSeasonDetailedResults_2017 <- read.csv("Data/2017_PrelimThruDay124_DetailedResults.csv")
  RegularSeasonDetailedResults_2017 <- read.csv("Data/2017_Final_DetailedResults.csv")
TourneyCompactResults <- read.csv("Data/TourneyCompactResults.csv")
TourneyDetailedResults <- read.csv("Data/TourneyDetailedResults.csv")
# TourneySeeds <- read.csv("Data/TourneySeeds.csv")
TourneySeeds <- read.csv("Data/TourneySeeds_Thru2017_Better.csv")
# TourneySlots <- read.csv("Data/TourneySlots.csv")
TourneySlots <- read.csv("Data/TourneySlots_Thru2017_Better.csv")
sample_submission <- read.csv("Data/sample_submission.csv")
  sample_submission_5050_benchmark <- read.csv("Data/SampleSubmission_5050Benchmark.csv")


# Data from Discussion Forum: (https://www.kaggle.com/c/march-machine-learning-mania-2017/discussion)
game_flow_details_2010_2014 <- read.csv("Data/game_flow_details_2010-2014.csv")
massey_ordinals_2003_2016 <- read.csv("Data/massey_ordinals_2003-2016.csv")
# massey_ordinals_2017 <- read.csv("Data/MasseyOrdinals_2017_PrelimThruDay128_69systems.csv")
# massey_ordinals_2017 <- read.csv("Data/MasseyOrdinals_2017_ThruDay133_42systems.csv")
# massey_ordinals_2017 <- read.csv("Data/MasseyOrdinals_2017_ThruDay133_52systems.csv")
massey_ordinals_2017 <- read.csv("Data/MasseyOrdinals_2017_ThruDay133_68systems.csv")


pomeroy_ratings <- read.csv("Data/PomeryRatings.csv")

sagarin_ratings <- read.csv("Data/sagarin_ratings.csv")
sagarin_ratings <- filter(sagarin_ratings, !grepl("Basketball", sagarin))
sagarin_ratings <- filter(sagarin_ratings, !grepl("RATING", sagarin))
sagarin_ratings <- filter(sagarin_ratings, !grepl("ADVANTAGE", sagarin))
sagarin_ratings <- droplevels(sagarin_ratings)
sagarin_ratings$sagarin <- gsub("[[:blank:]]{2,}", " ", sagarin_ratings$sagarin[])
sagarin_ratings$sagarin <- gsub("([[:digit:]])([[:blank:]])", "\\1;", sagarin_ratings$sagarin[])
sagarin_ratings$sagarin <- gsub(" = ", ";", sagarin_ratings$sagarin[])
sagarin_ratings$sagarin <- gsub("[|][[:blank:]]", "", sagarin_ratings$sagarin[])
sagarin_ratings$sagarin <- gsub("[\\(][[:blank:]]", ";", sagarin_ratings$sagarin[])
sagarin_ratings$sagarin <- gsub("[\\)][[:blank:]]", ";", sagarin_ratings$sagarin[])
sagarin_ratings$sagarin <- gsub("\\(ETS= ", ";", sagarin_ratings$sagarin[])
sagarin_ratings$sagarin <- trimws(sagarin_ratings$sagarin)
sagarin_ratings <- separate(sagarin_ratings, sagarin, c("pom_rank", "Team_Name", "RATING", "W", "L", "SCHEDL", "SCHEDL_rank", "VS_top25_W", "VS_top25_L", "VS_top50_W", "VS_top50_L", "PREDICTOR", "PREDICTOR_rank", "GOLDEN_MEAN", "GOLDEN_MEAN_rank", "RECENT", "RECENT_rank"), sep = ";", remove = TRUE)
write.csv(sagarin_ratings, file = "Data/sagarin_ratings_cleaned.csv", row.names = FALSE, quote = FALSE)

rpi <- read.csv("Data/teamrankings_RPI.csv")
rpi$rpi <- gsub("[[:blank:]]{2,}", " ", rpi$rpi[])
rpi$rpi <- gsub("([[:digit:]])([[:blank:]])", "\\1;", rpi$rpi[])
rpi$rpi <- gsub("[[:blank:]][\\(]", ";", rpi$rpi[])
rpi$rpi <- gsub("[\\)][[:blank:]]", ";", rpi$rpi[])
rpi$rpi <- gsub("-", ";", rpi$rpi[])
rpi$rpi <- gsub(";FL\\)", " FL", rpi$rpi[])
rpi$rpi <- gsub(";PA\\)", " PA", rpi$rpi[])
rpi$rpi <- gsub(";OH\\)", " OH", rpi$rpi[])
rpi$rpi <- gsub(";NY\\)", " NY", rpi$rpi[])
rpi$rpi <- gsub(";NC;", ";NC ", rpi$rpi[])
rpi$rpi <- gsub(";TX;", ";TX ", rpi$rpi[])
rpi$rpi <- gsub(";WI;", ";WI ", rpi$rpi[])
rpi$rpi <- gsub(";TX A&M;", ";TX A&M ", rpi$rpi[])
rpi$rpi <- gsub(";Loyola;", ";Loyola ", rpi$rpi[])
rpi$rpi <- gsub(";Gard;", ";Gard ", rpi$rpi[])
rpi$rpi <- gsub(";LIU;", ";LIU ", rpi$rpi[])
rpi$rpi <- gsub(";IL;", ";IL ", rpi$rpi[])
rpi$rpi <- gsub(";Beth;", ";Beth ", rpi$rpi[])
rpi$rpi <- trimws(rpi$rpi)
rpi <- separate(rpi, rpi, c("rpi_rank", "Team_Name", "W", "L", "RATING", "rpi_rank_high", "rpi_rank_low", "rpi_rank_last"), sep = ";", remove = TRUE)
write.csv(rpi, file = "Data/teamrankings_RPI_cleaned.csv", row.names = FALSE, quote = FALSE)

bpi <- read.csv("Data/teamrankings_BPI.csv")
bpi$bpi <- gsub("[[:blank:]]{2,}", " ", bpi$bpi[])
bpi$bpi <- gsub("([[:digit:]])([[:blank:]])", "\\1;", bpi$bpi[])
bpi$bpi <- gsub("\t", ";", bpi$bpi[])
bpi$bpi <- trimws(bpi$bpi)
bpi <- separate(bpi, bpi, c("bpi_rank", "Team_Name", "Conference", "W-L", "bpi_off", "bpi_def", "bpi_rating", "seven_day_rank_change"), sep = ";", remove = TRUE)
write.csv(bpi, file = "Data/teamrankings_BPI_cleaned.csv", row.names = FALSE, quote = FALSE)

fivethirtyeight <- read.csv("Data/teamrankings_fivethirtyeight.csv")
fivethirtyeight$ns538 <- gsub("[[:blank:]]{2,}", " ", fivethirtyeight$ns538[])
fivethirtyeight$ns538 <- gsub("([[:digit:]])([[:blank:]])", "\\1;", fivethirtyeight$ns538[])
fivethirtyeight$ns538 <- gsub("\t", ";", fivethirtyeight$ns538[])
fivethirtyeight <- filter(fivethirtyeight, !grepl("%", ns538))
fivethirtyeight$ns538 <- gsub("([[:blank:]])([[:digit:]])", ";\\2", fivethirtyeight$ns538[])
fivethirtyeight$ns538 <- gsub(";âˆš;", "", fivethirtyeight$ns538[])
fivethirtyeight$ns538 <- gsub("[;]$", "", fivethirtyeight$ns538[])
fivethirtyeight$ns538 <- trimws(fivethirtyeight$ns538)
fivethirtyeight <- separate(fivethirtyeight, ns538, c("Team_Name", "Seed", "Region", "Rating"), sep = ";", remove = TRUE)
write.csv(fivethirtyeight, file = "Data/teamrankings_fivethirtyeight_cleaned.csv", row.names = FALSE, quote = FALSE)

massey <- read.csv("Data/teamrankings_massey.csv")
massey$massey <- gsub("\t", ";", massey$massey[])
massey$massey <- gsub("[;]$", "", massey$massey[])
massey <- separate(massey, massey, c("Team_Name", "Conference", "Record", "Win_Percent", "Delta", "Rank", "Rating", "Power_Rank", "Power", "Offense_Rank", "Offense", "Defense_Rank", "Defense", "HFA", "SoS_Rank", "SoS", "SSF_Rank", "SSF", "EW", "EL"), sep = ";", remove = TRUE)
write.csv(massey, file = "Data/teamrankings_massey_cleaned.csv", row.names = FALSE, quote = FALSE)



kenpom <- read.csv("Data/teamrankings_kenpom.csv")


playerdata_roster <- read.csv("Data/playerdata_roster.csv")
playerdata_statistics <- read.csv("Data/playerdata_statistics.csv")
SeedRoundSlots <- read.csv("Data/SeedRoundSlots.csv")
TeamCoaches <- read.csv("Data/TeamCoaches_PrelimThru2017Day87.csv")
TeamConferences_Thru2017 <- read.csv("Data/TeamConferences_Thru2017.csv")
TeamSpellings <- read.csv("Data/TeamSpellings.csv")
TourneyGeog <- read.csv("Data/TourneyGeog.csv")
point_spreads <- read.csv("Data/point_spreads.csv") # https://www.kaggle.com/c/march-machine-learning-mania-2017/discussion/30061

devtools::install_github('zachmayer/kaggleNCAA')


# - #